#!/usr/bin/env python3
import os
import re
from pathlib import Path

CONTENT_DIR = Path('/root/.openclaw/workspace/aidetector-site/content/detect')
stats = {'audited': 0, 'fixed': 0}

bad_patterns = [
    r'Generated by Ghostwriter',
    r'BTC Macro Radar System',
    r'学术诚信指南',
    r'军备竞赛',
]
compiled = [re.compile(p, re.IGNORECASE) for p in bad_patterns]

for path in CONTENT_DIR.glob('*.md'):
    text = path.read_text(encoding='utf-8')
    stats['audited'] += 1
    original = text

    # 轻度去模板痕迹
    text = text.replace('n- high-stakes', '- high-stakes')
    text = re.sub(r'\n{3,}', '\n\n', text)

    # 清理明显旧模板词
    for pat in compiled:
        text = pat.sub('', text)

    if text != original:
        path.write_text(text, encoding='utf-8')
        stats['fixed'] += 1

print(f"✅ Full audit complete: audited={stats['audited']}, fixed={stats['fixed']}")
